= About
:page-description: TechWriter.Dev focuses on technical writing from the perspective of a software developer.
:page-layout: page
:page-permalink: /about
:imagesdir: assets
:stem: latexmath
:experimental: true

== Purpose of this Site

=== The Audience
The domain name, TechWriter.Dev, was chosen with the intention of evoking a close connection between the two professions, _technical writing_ and _software development_.
As history repeats itself, what was once out of fashion becomes in fashion again, as we witness a new trend of tech-savvy technical writers using lightweight markup with a text editor treating documentation like code. This is in stark contrast to an early 21st century trend of embracing overly complex,  DTP-style, https://en.wikipedia.org/wiki/WYSIWYG[WYSIWYG] applications. This new _agile_ trend brings me full circle to similar tools and workflow I had in my hybrid role of copy editor, translator, and stem:[\LaTeX{}] "`typesetter`" while a graduate student at the Univerisität Siegen, Germany in the late 1980`'s and early 1990`'s.
The goal of this website is to provide resources to software developers and technical writers in a time when their tools and workflows are becoming increasingly similar.

=== Technical Resources
Fellow professionals who find themselves anywhere on the spectrum between "`technical writer`" and "`software developer`" will find examples of how I found my way in this brave new world of "`treating documentation like code.`"
I am currently in the process of adding "`How-To`'s`" for all the technical situations I have found myself in over the years.

The bulk of my future posts will be centered around my specific area of expertise: using MongoDB in a PHP environment and migrating highly normalized relational data with complex joins to more sane, single-collection, single-query, MongoDB document schemata with multi-dimensional, nested arrays that perfectly match the real world model: what application developers still have to create in their application code manually (with the relational model), because SQL cannot deliver tree-like data structures.

=== In Case Your Company`'s Needs Match My Experience and Skills
Any company seeking my services as a technical writer will find alongside my link:/cv[résumé] a limited but ever-increasing portfolio of my work.

If you are looking for someone with Adobe InDesign, Visio, Microsoft Office, or Confluence experience who can't tell Java from JavaScript, then maybe you are actually looking for a "`graphic designer`" (or in the case of Visio, maybe a project/product manager) instead. I do API documentation of code written by software developers, not glossy marketing brochures.
