= Résumé
:page-description: Résumé of John Kirch, technical writer and web developer. Skills: LaTeX, AsciiDoc, Jekyll, MongoDB, JavaScript, JSON, SQL, RESTful API, PHP, Perl, etc.
:page-layout: page
:page-permalink: /cv
:sectlinks: true
:toc: left
Created with Asciidoctor PDF
v2.1.5, 2019-05-19

== Experience Synopsis
Decades of experience in various IT roles requiring excellent analytical skills has resulted in a proven track record of focusing on employers`' goals and how to best achieve those goals _in addition to_ following process and completing tasks on a storyboard.

Major areas of expertise:

. *Language*, both natural and machine/programming languages, their grammar, syntax, morphology, and semantics.
* English and German composition, especially in my roles where the focus was on the creation of publications and technical documentation.
* Using programming languages to store/retrieve/display/analyze data for human consumption.
* Excellent command of English grammar rules such that listening to others speak often results in the thought, "`How many Americans know what a https://dictionary.cambridge.org/grammar/british-grammar/pronouns/relative-pronouns[relative pronoun] is and when to use it?`"
. *Logic* and sound reasoning embodied in an *analytical thought* process. Analytical thinking has been associated with https://blog.mindvalley.com/analytical-thinking-skills/[a number of different skills], some of which are:
* _Problem solving:_ Never encountered a software bug or design issue that could not be traced back to a root cause or alleviated via an alternative design strategy.
* _Creativity:_ The analytical mind quite often thinks in visual terms. Being able to recognize patterns in anything and everything allows one to quickly visualize data and create database schemata that most accurately mimic the structure or relationships found in real world processes.
* _Organization:_ The logical grouping of different but related topics when writing a paper, article or documentation necessitates organizing the structure of a document first as an outline, a best practice which is a strict requirement for any serious writer.
* _Communication:_ Getting a _clear, concise and unambiguous_ message across to readers using terse language and terminology appropriate to the subject matter, is the primary goal of any analytically oriented technical writer.

== Professional Experience

=== Gap Inc, Corporate Headquarters, San Francisco, CA. (Jul 2009 - Feb 2019) +
[maroon]#*(100% remote since January 2015)*#

Despite having four different titles/positions and nine different supervisors over an almost 10 year career at Gap Inc, there was one constant: continuously contributing back-end web application code for the "`CPM Toolbox,`" an integrated suite of web applications for managing construction projects.
These contributions relative to the team as a whole are best visualized in this link:assets/GitHubCommits_CPM-Toolbox_20090726-20190222.png[GitHub graph].

==== Software Engineer III (Jul 2016 - Feb 2019)
* Created a comprehensive set of technical documentation targeted at our developers for the Materials and Visual Merchandise Procurement tool within our suite of web applications.
* Extended existing APIs and created new APIs to facilitate rapid application development.
* Oversaw the technical design of new web applications within the scope of an Agile Development environment.
* Provided technical guidance and training to web application developers.
* Designed data models for new and existing web applications.
* Reviewed code and provided feedback for application developers.
* Created training materials for application developers in the form of videos and online documentation that provided real life code samples along with the results of those code examples in real time.
* Created migration scripts for migrating highly normalized relational data to NoSQL (MongoDB) for certain web applications that have historically suffered under the relational data model.
* Administered AWS instances, S3 data, and disaster recovery strategies.
* Planned and administered server configurations for both database and web servers.
* Designed, deployed and monitored our own security model at the network, host, server and application levels.
* Wrote and maintained shell scripts for automated deployment of new features to our production, staging, training, and multiple test environments when specific Git branches`' commits are pushed to specific repositories.

==== Manager / Technical Lead (Oct 2011 - Jul 2016)

* Used `doxygen` to create API documentation of our PHP code.
* Created a "`Best Practices of Web Development`" link:/2016/09/06/Best-Practices-of-Web-Development.html[document] for our developers to reference.
* Met with stakeholders and assisted them in composing new user stories and prioritizing them.
* Mentored a team of web developers in best coding practices, database design, (AWS) cloud-based system administration, and how to effectively use Git.
* Managed a team of web developers and functioned as the Product Owner within the scope of Scrum.
* Created and maintained a custom object-oriented PHP framework that would ensure backwards compatibility with our legacy suite of web applications.

==== Web Developer / Technical Lead (Jan 2010 - Oct 2011)
* Senior web architect for a large, in-house B2B suite of web applications linking suppliers, consolidators, architects, and general contractors with our construction project management staff to manage the construction operations of 1,500+ stores in the US and Canada.
* Developed a complex set of tools supporting project-role authentication, bid analysis, workflow (multi-tier approval process), revision control of submitted forms during the approval process, document management and more.
* Provided over 1,300 registered users with the best web experience possible.

==== Web Developer Consultant (Ascent Services) (Jul 2009 - Jan 2010)
* Maintained and developed new web applications.

=== Back-end Web Developer at Media Net Link Inc, San Ramon, CA (May 2007 - Jun 2009)
* Provided http://mnl.com/services/app_dev.php[web development services] for Cisco Systems internal business/sales capacity planning website using Perl CGI and Oracle 10g on a Solaris platform.
* Designed and developed PHP modules and PostgreSQL database schemata for both existing and emerging web products.
* Worked closely with front-end web developers to produce custom web applications for our clients.

=== ESOL Adjunct Professor at Northwest Florida State College, Niceville, FL (Aug 2006 - Apr 2007)
* Taught ESOL classes at 2 campuses.
* Taught ABE (Adult Basic Education) classes.


=== Copy Editor at Al-Adly Publications (Jun 2005 - May 2006)
* Copy editor for various publications.
* Provided consulting and technical support for the publication process.

=== Applications Specialist at the University of Texas at Austin, Germanic Studies, Austin, TX (Jan 2002 - Oct 2004)
* System administration of a departmental web server.
* Developed and maintained custom web applications for two separate websites:
** An internal site for staff to reconcile around 50 financial accounts
** A public site to provide details for current classes: Abstract, Syllabus, Reading Lists, etc.
* Provided desktop support to faculty and staff.

=== System QA Engineer at Vignette (now OpenText), Austin, TX (Jan 2001 - Apr 2001)
* Built configurations for QA testing.
* Maintained a custom PHP web application for providing metrics on QA test results.

=== Support Engineer at Tivoli/IBM, Austin, TX (Jan 1998 - Dec 2001)
* Provided level 2 customer support for the http://www.softpanorama.org/Admin/Tivoli/TEC/index.shtml[Tivoli Enterprise Console].
* Built similar http://publib.boulder.ibm.com/tividd/td/tec/SC32-1233-00/en_US/PDF/ecoimst.pdf[server configurations] on AIX, HP-UX, and Solaris platforms connected to a required database server (DB2, Oracle, or Sybase) to replicate customers`' configurations as closely as possible.
* Designed and maintained a team website for managing a knowledge base of support-centric issues.

=== UNIX (Solaris) Consultant at the Texas Department of Human Services, Austin, TX (Sep 1997 - Jan 1998)
* Worked through two consulting agencies (https://www.appliedis.com/[Applied Information Sciences, Inc.] and https://www.geologics.com/[GeoLogics Corporation])
* Was part of the GeoLogics team that was tasked with deploying https://en.wikipedia.org/wiki/CA_Harvest_Software_Change_Manager[CCC/Harvest] (was later acquired by CA), an SCM client/server system that was to be used in preparation for the Y2K event.
* Single-handedly wrote a scheduler in `sybperl` as a consultant working through Applied Information Sciences to automate the execution of several `sybperl` scripts that had to be run at various times of the month (some by specific weekdays, others by day of the month) many of which with dependencies, for example, script _y_ is only launched on successful completion of script _x_, otherwise run script _z_, etc.
No test environment was available.
This had to be developed in the production environment.
If it did not work, thousands of Texans on welfare would not receive their benefits.
It worked the first time without any complications.

=== Desktop Support Specialist at IXC Communications*, Austin, TX (Dec 1996 - May 1997)
* Provided support to over 100 users on Windows NT, Solaris, and Novell networks.

*Acquired by Cincinnati Bell Inc in 1999, then Broadwing Corporation in 2004, and then Level 3 Communications in 2007.

=== Student Assistant, Fachbereich 3 (Liberal Arts), Universität Siegen, Siegen, Germany -- (1988 - 1993)
* Translated German correspondence into English for https://de.wikipedia.org/wiki/Helmut_Kreuzer[Professor Helmut Kreuzer].
* Proofread and edited English language abstracts and articles.
* Typeset an entire publication using https://en.wikipedia.org/wiki/LaTeX[`LaTeX`], https://www.booklooker.de/B%C3%BCcher/Hartmut-Hrsg-Froeschle+Suevica-Band-6-Beitr%C3%A4ge-zur-schw%C3%A4bischen-Literatur-und-Geistesgeschichte/id/A024nT0z01ZZw[_Suevica: Band 6 -- Beiträge zur schwäbischen Literatur- und Geistesgeschichte_, Hartmut Fröschle (Hrsg.), Stuttgart, Hans-Dieter Heinz Akademischer Verlag, 1991.]

=== R&D FORTRAN Programmer at Chevron Geosciences Company, Houston, TX (Dec 1979 - Dec 1984)
* Data processing of geophysical data (first 6 months on the job).
* Systems support for mainframe issues on jobs submitted from Calgary (for about 4 months).
* Served as a FORTRAN programmer testing new experimental algorithms in R&D, a small team of five engineers, which included Chevron's Chief Geophysicist, Roger Judson, and two other senior geophysicists.

=== Summer Internship at Fairfield Industries, 10052 Harwin Dr, Houston, TX (Jun 1979 - Nov 1979)
* This internship was offered while touring the various Houston-based oil exploration companies as part of the link:#_honors-and-awards[SEG Special Award] received at the 29^th^ International Science and Engineering Fair.
* Coded geometry for ¼ millisecond, high resolution, marine seismic data.

== Education, Training and Certifications
* https://www.coursera.org/account/accomplishments/verify/PMZE8V3JHTDP[Machine Learning], Stanford taught by Andrew Ng, 07/13/2017.
* CELTA: University of Cambridge Certificate in TEFL, https://passthecelta.com/faq/how-is-the-celta-graded/[Pass (Grade B)], awarded 01/17/2005. Center Number US072, Accreditation Number 100/2664/2, Certificate Number ccpf214887.
* BA, University of Texas at Austin, Austin, TX, Summer 1996, Major: German, GPA 3.916
* _Zwischenprüfung_, Universität Siegen, Siegen, Germany. Master`'s program. Major: Medieval German Literature and Linguistics. Minor: English Literature and Linguistics.

== Publications
* Kirch, John. "`Microsoft Windows NT Server 4.0 versus UNIX.`" _AUUGN_ (the journal of the Australian Unix Users`' Group) 19, no. 3 (August 1998): 12–27. +
The popularity of the
link:nt-vs-unix/en.html[online version], from which the _AUUGN_ print edition was derived, was so enormous that volunteers translated it into
link:nt-vs-unix/cn[Chinese], Croatian,
link:nt-vs-unix/cz.html[Czech],
link:nt-vs-unix/fr.html[French],
link:nt-vs-unix/de.html[German],
link:nt-vs-unix/id.html[Indonesian],
link:nt-vs-unix/jp.html[Japanese],
link:nt-vs-unix/kr.html[Korean],
link:nt-vs-unix/pt.html[Portuguese],
link:nt-vs-unix/ru.html[Russian], and Spanish.
* Zalan, S.E., Roger Judson, and John Kirch. "`Optimal Use of Iterative Stacking.`" Paper presented at the Intercompany Geophysical Conference by Chevron Geosciences Company, Incline Village, NV, October 21–26, 1984.

== Honors and Awards
* **One year, Full Stipendium from the https://en.wikipedia.org/wiki/German_Academic_Exchange_Service[DAAD]** for participating in a **Masters Program at the Universität Siegen, Germany** +
Only two recipients were chosen each year based on academic excellence within the German Studies Department at the University of Houston. The official letter from the Universität Siegen is dated May 14, 1986.
* **29^th^ International Science & Engineering Fair, Anaheim, CA. May 1978** +
** **Special Award** from the **AAPG** (American Association of Petroleum Geologists) +
Received full tuition and travel expenses paid for attending the https://fieldcamp.missouri.edu/camp-history[University of Missouri Geology Field Camp at the Branson Field Laboratory], located in the Shoshone National Forest near Lander, Wyoming.
** ** Special Award** from the https://seg.org[SEG] +
One of only two recipients awarded a 5-day tour of various seismic exploration companies in Houston, including Fairfield Industries, specializing in high resolution offshore oil exploration.
Was offered a summer internship at Fairfield Industries.
* **28^th^ International Science & Engineering Fair, Cleveland, OH. May 1977** +
**Special Award** from the https://seg.org[SEG] +
One of only two recipients awarded a 5-day tour of various seismic exploration companies in Houston, including Seiscom-Delta Corporation and a chance to spend an afternoon with https://en.wikipedia.org/wiki/Robert_E%2E_Sheriff[Robert E. Sheriff] who inscribed a copy of his https://library.seg.org/doi/book/10.1190/1.9781560802969[_Encyclopedic Dictionary of Exploration Geophysics_], Society of Exploration Geophysicists, 1973.
