= Curriculum Vitae
:page-layout: page
Created with Asciidoctor PDF
v1.0.4, 2019-04-08

== Experience Synopsis
With almost 40 years of experience in various IT roles requiring excellent analytical skills I have a proven track record of focusing on my clients`'/employers`' goals (never losing track of "`the big picture`") and how to best achieve those goals _in addition to_ following process and completing tasks on a storyboard.

Major areas of expertise:

. *Language*, both natural and machine/programming languages, their grammar, syntax, morphology, and semantics.
* English and German composition, e.g. as in my roles where the focus was on the creation of publications and technical documentation.
* Using programming languages to store/retrieve/display/analyze data for human consumption.
* Being one of the few remaining Americans who know what a relative pronoun is and when to use it. Having excellent command of English grammar rules such that I cringe every time I hear the nominative case (_I_) misused for the objective case (_me_), e.g. _The test would be simple for **you or I**._
(_Chicago Manual of Style 17_, https://www.chicagomanualofstyle.org/book/ed17/part2/ch05/psec037.html[ 5.37: Nominative case misused for objective ])
. *Logic* and sound reasoning embodied in an *analytical thought* process. Analytical thinking has been associated with https://blog.mindvalley.com/analytical-thinking-skills/[a number of different skills], some of which are:
* _Problem solving:_ I have never encountered a software bug or design issue that I could not solve.
* _Creativity:_ The analytical mind quite often thinks in visual terms. Being able to recognize patterns in anything and everything allows me to quickly visualize data and create database schemata that most accurately mimic the structure found in real life.
* _Organization:_ The logical grouping of different but related topics when writing a paper, article or documentation necessitates organizing the structure of any document first as an outline.
* _Communication:_ Getting a _clear, concise and unambiguous_ message across to readers using terse language and terminology appropriate to the subject matter, is the primary goal of any analytically oriented technical writer.

== Professional Experience

=== Gap Inc, Corporate Headquarters, San Francisco, CA. (Jul 2009 - Feb 2019) +
(100% remote since January 2015)

==== Software Engineer III (Jul 2016 - Feb 2019)
* Oversaw the technical design of new web applications within the scope of an Agile Development environment.
* Provided technical guidance and training to web application developers.
* Designed data models for new and existing web applications.
* Extended existing APIs and created new APIs to facilitate rapid application development.
* Reviewed code and provided feedback for application developers.
* Created training materials for application developers in the form of videos and online documentation that provided real life code samples along with the results of those code examples in real time.
* Created migration scripts for migrating highly normalized relational data to NoSQL (MongoDB) for certain web applications that have historically suffered under the relational data model.
* Administered AWS instances, S3 data, and disaster recovery strategies.
* Planned and administered server configurations for both database and web servers.
* Designed, deployed and monitored our own security model at the network, host, server and application levels.
* Wrote and maintained shell scripts for automated deployment of new features to our production, staging, training, and multiple test environments when specific Git branches`' commits are pushed to specific repositories.
* Created a comprehensive set of technical documentation targeted at our developers for the Materials and Visual Merchandise Procurement tool within our suite of web applications.

==== Manager / Technical Lead (Oct 2011 - Jul 2016)
* Managed a team of web developers and function as the Product Owner within the scope of Scrum.
* Met with stakeholders and assisted them in composing new user stories and prioritizing them.
* Created and maintained a custom object-oriented PHP framework that will ensure backwards compatibility with our legacy suite of web applications.
* Use `doxygen` to create API documentation of our PHP code.
* Created a "`Best Practices`" online web document for our developers to reference.
* Mentored my team of web developers in best coding practices, database design, (AWS) cloud-based system administration, and getting the best out of `Git`.

==== Web Developer / Technical Lead (Jan 2010 - Oct 2011)
* Senior web architect for a large, in-house B2B suite of web applications linking suppliers, consolidators, architects, and general contractors with our construction project management staff to manage the construction operations of 1,500+ stores in the US and Canada.
* Developed a complex set of tools supporting project-role authentication, bid analysis, workflow (multi-tier approval process), revision control of submitted forms during the approval process, document management and more.
* Provided over 1,300 registered users with the best web experience possible.

==== Web Developer Consultant (Ascent Services) (Jul 2009 - Jan 2010)
* Maintained and developed new web applications.

=== Back-end Web Developer at Media Net Link Inc, San Ramon, CA (May 2007 - Jun 2009)
* Provided http://mnl.com/services/app_dev.php[web development services] for Cisco Systems internal business/sales capacity planning website using Perl CGI and Oracle 10g on a Solaris platform.
* Designed and developed PHP modules and PostgreSQL database schemata for both existing and emerging web products.
* Worked closely with front-end web developers to produce custom web applications for our clients.

=== ESOL Adjunct Professor at Northwest Florida State College, Niceville, FL (Aug 2006 - Apr 2007)
* Taught ESOL classes at 2 campuses.
* Taught ABE (Adult Basic Education) classes.


=== Copy Editor at Al-Adly Publications (Jun 2005 - May 2006)
* Copy editor for various publications.
* Provided consulting and technical support for the publication process.

=== Applications Specialist at the University of Texas at Austin, Germanic Studies, Austin, TX (Jan 2002 - Oct 2004)
* System administration of a departmental web server.
* Developed and maintained custom web applications for two separate websites:
** An internal site for staff to reconcile around 50 financial accounts
** A public site to provide details for current classes: Abstract, Syllabus, Reading Lists, etc.
* Provided desktop support to faculty and staff.

=== System QA Engineer at Vignette (now OpenText), Austin, TX (Jan 2001 - Apr 2001)
* Built configurations for QA testing.
* Maintained a custom PHP web application for providing metrics on QA test results.

=== Support Engineer at Tivoli/IBM, Austin, TX (Jan 1998 - Dec 2001)
* Provided level 2 customer support for the http://www.softpanorama.org/Admin/Tivoli/TEC/index.shtml[Tivoli Enterprise Console].
* Built similar http://publib.boulder.ibm.com/tividd/td/tec/SC32-1233-00/en_US/PDF/ecoimst.pdf[server configurations] on AIX, HP-UX, and Solaris platforms connected to a required database server (DB2, Oracle, or Sybase) to replicate customers`' configurations as closely as possible.
* Designed and maintained a team website for managing a knowledge base of support-centric issues.

=== UNIX (Solaris) Consultant at the Texas Department of Human Services, Austin, TX (Sep 1997 - Jan 1998)
* Worked through two consulting agencies (https://www.appliedis.com/[Applied Information Sciences, Inc.] and https://www.geologics.com/[GeoLogics Corporation])
* For GeoLogics I was part of a team that was deploying https://en.wikipedia.org/wiki/CA_Harvest_Software_Change_Manager[CCC/Harvest] (was later acquired by CA), an SCM client/server system that was to be used in preparation for the Y2K event.
* For Applied Information Sciences I single-handedly wrote a scheduler in `sybperl` to automate the execution of several `sybperl` scripts that needed to run at various times of the month (some by specific weekdays, others by day of the month) many of which with dependencies, e.g. script _y_ is only launched on successful completion of script _x_, otherwise run script _z_, etc. No test environment was available. This had to be developed in the production environment. If it did not work, thousands of Texans on welfare would not receive their benefits. It worked the first time without any complications.

=== Desktop Support Specialist at IXC Communications*, Austin, TX (Dec 1996 - May 1997)
* Provided support to over 100 users on Windows NT, Solaris, and Novell networks.

*Acquired by Cincinnati Bell Inc in 1999, then Broadwing Corporation in 2004, and then Level 3 Communications in 2007.

=== Student Assistant, Fachbereich 3 (Liberal Arts), Universität Siegen, Siegen, Germany -- (1988 - 1993)
* Translated German correspondence into English for https://de.wikipedia.org/wiki/Helmut_Kreuzer[Professor Helmut Kreuzer].
* Proofread and edited English language abstracts and articles.
* Typeset an entire publication using https://en.wikipedia.org/wiki/LaTeX[`LaTeX`], https://www.booklooker.de/B%C3%BCcher/Hartmut-Hrsg-Froeschle+Suevica-Band-6-Beitr%C3%A4ge-zur-schw%C3%A4bischen-Literatur-und-Geistesgeschichte/id/A024nT0z01ZZw[_Suevica: Band 6 -- Beiträge zur schwäbischen Literatur- und Geistesgeschichte_, Hartmut Fröschle (Hrsg.), Stuttgart, Hans-Dieter Heinz Akademischer Verlag, 1991.]

=== R&D FORTRAN Programmer at Chevron Geosciences Company, Houston, TX (Dec 1979 - Dec 1984)
* Data processing of geophysical data (first 6 months on the job).
* Systems support for mainframe issues on jobs submitted from Calgary (for about 4 months).
* Served as a FORTRAN programmer in R&D for testing new algorithms where I worked closely with Chevron's Chief Geophysicist, Roger Judson.

=== Summer Internship at Fairfield Industries, 10052 Harwin Dr, Houston, TX (Jun 1979 - Nov 1979)
* This internship was offered to me when I was touring the various Houston-based oil exploration companies, i.e. the SEG Special Award I received at the 28^th^ International Science and Engineering Fair.
* Coded geometry for 1/4 millisecond, high resolution, marine seismic data.

== Education, Training and Certifications
* https://www.coursera.org/account/accomplishments/verify/PMZE8V3JHTDP[Machine Learning], Stanford taught by Andrew Ng, 07/13/2017.
* CELTA: University of Cambridge Certificate in TEFL, https://passthecelta.com/faq/how-is-the-celta-graded/[Pass (Grade B)], awarded 01/17/2005. Center Number US072, Accreditation Number 100/2664/2, Certificate Number ccpf214887.
* BA, University of Texas at Austin, Austin, TX, Summer 1996, Major: German, GPA 3.916
* _Zwischenprüfung_, Universität Siegen, Siegen, Germany. Master`'s program. Major: Medieval German Literature and Linguistics. Minor: in English Literature and Linguistics.

== Publications
* Kirch, John. "`Microsoft Windows NT Server 4.0 versus UNIX.`" _AUUGN_ (the journal of the Australian Unix Users`' Group) 19, no. 3 (August 1998): 12–27. +
The popularity of the online version, from which the _AUUGN_ print edition was derived, was so enormous that volunteers translated it into Chinese, Croatian, Czech, French, German, Indonesia, Japanese, Korean, Portuguese, Russian, and Spanish.
* Zalan, S.E., Roger Judson, and John Kirch. "`Optimal Use of Iterative Stacking.`" Paper presented at the Intercompany Geophysical Conference by Chevron Geosciences Company, Incline Village, NV, October 21–26, 1984.

== Honors & Awards
* **One year, Full Stipendium from the https://en.wikipedia.org/wiki/German_Academic_Exchange_Service[DAAD]** for participating in a **Masters Program at the Universität Siegen, Germany** +
Only two recipients were chosen each year based on academic excellence within the German Studies Department at the University of Houston. The official letter from the Universität Siegen is dated May 14, 1986.
* **29^th^ International Science & Engineering Fair, Anaheim, CA. May 1978** +
** **Special Award** from the **AAPG** (American Association of Petroleum Geologists) +
Received full tuition and travel expenses paid for attending the https://fieldcamp.missouri.edu/camp-history[University of Missouri Geology Field Camp at the Branson Field Laboratory], located in the Shoshone National Forest near Lander, Wyoming.
** ** Special Award** from the **SEG** (Society of Exploration Geophysicists) +
One of only two recipients awarded a 5-day tour of various Seismic Exploration Companies in Houston, including Fairfield Industries, specializing in high resolution offshore oil exploration.
Was offered a summer internship at Fairfield Industries.
* **28^th^ International Science & Engineering Fair, Cleveland, OH. May 1977** +
**Special Award** from the **SEG** (Society of Exploration Geophysicists) +
One of only two recipients awarded a 5-day tour of various Seismic Exploration Companies in Houston, including Seiscom-Delta Corporation and a chance to spend an afternoon with https://en.wikipedia.org/wiki/Robert_E%2E_Sheriff[Robert E. Sheriff] who inscribed to me a copy of his https://library.seg.org/doi/book/10.1190/1.9781560802969[_Encyclopedic Dictionary of Exploration Geophysics_], Society of Exploration Geophysicists, 1973.
